### ISSUE TITLE
Display line breaks in pink-box comments

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#1]
Currently line breaks in pink-box comments are not displayed (although they exist in the html source). I don't know whether this is intentional, but this is definitely painful for users and can be fixed easily by removing `white-space: normal;`.

**Comment by that-german** [comment]
Also oversized strings stretch the html to the point of being nearly unsuable, we should take care of that as well. Also warn people trying to enter a novel, we may even want to have a (generous) hard limit on number of lines.

**Comment by zabolotskii** [comment]
I'm not sure, but possibly oversized strings can be tamed by style="overflow-x: auto;" with some appropriate width restrictions.

**Comment by rsc** [comment]
Fixed.
