### ISSUE TITLE
Improve diff rendering

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#10]
This is a proposal of an enhancement which is a part of a larger project, UI renovation. This proposal is probably relatively easy to implement.

In the OEIS, we frequently add or remove brackets, minuses, and underscores. The default rendering of the `ins` and `del` tags (they are used in the diffs) as underline and strikethrough are acceptable for words but sub-optimal for this kind of characters.

In a perfect inline diff, I would suggest smth like thin green underline with light-green background for `ins` and thin red strikethrough with light-red background for `del`. Controlling thickness of underline and strikethrough is tricky though. However, even just making them colored would allow to easily distinguish <ins>&nbsp;</ins> vs _ and <del>&nbsp;</del> vs -, which would be really nice.

**Comment by rsc** [comment]
Done.
