### ISSUE TITLE
Account registration process improvement

### ISSUE THREAD

**Issue by archmageirvine** [oeis/oeis#11]
During account registration many account are placed on hold due to insufficient information.

At the moment there is one box for the biography which is serving two purposes (the initial content of the User Page and the evidence the person is genuine).  A lot of people are naturally reticent to provide personal information which will then be publicly reflected. Other people put some evidence they are real but don't really say much about their interests.

If we had a separate (unpublished) box for providing additional evidence supporting registration, then we might save a lot of effort in applications that are currently put on hold and follow up on admin.

**Comment by rsc** [comment]
I'd rather not collect that information into MediaWiki. Corresponding over email is sufficient. It is also not a goal to register people as quickly as possible. The goal is to register people who understand that the OEIS is a mathematical reference and that submissions needs to be at that bar.
