### ISSUE TITLE
URL in the "[editor] published your changes" email

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#12]
This is a proposal of an enhancement which is probably relatively easy to implement.

Whenever a draft started by a contributor is proposed, reviewed, or approved by another person, the OEIS software sends them an email saying: "Visit http\://oeis.org/draft/A****** for the latest revision". (By the way, it would probably be better to replace http by https here.) For proposed changes, this is correct and convenient. But when the email says that an editor published your changes, the linked page becomes empty and thus almost useless. In that case, the URL should probably point to the sequence entry itself: https\://oeis.org/A******

**Comment by rsc** [comment]
Fixed.
