### ISSUE TITLE
List of current revisions of all sequences

### ISSUE THREAD

**Issue by gfis** [oeis/oeis#16]
There is a revision number and time in the JSON format of every sequence:
>     "revision": 16,
>     "time": "2022-07-05T11:39:34-04:00",
I find this revision only in the JSON (neither in the internal format, nor in the `cat25` dump).
For my regular consistency checks I currently try to derive changed/new sequences from a search for keywords "changed" resp. "new", but that procedure is error prone and may cause unnecessary downloads.
Therefore I would really appreciate a very simple, daily list (`A-number, rev, time`) provided in parallel to `stripped, names, bfiledir`.

**Comment by rsc** [comment]
I changed the %I line to add #rev mtime to the end of the line, which you can see by viewing the text format of any sequence, such as https://oeis.org/search?q=id:A178939&fmt=text.

That change to the text format will be reflected in the cat25 file and the oeis/oeisdata repo when those are regenerated in the next nightly update.
