### ISSUE TITLE
`cons` doesn't work properly with some offsets

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#17]
As per https://oeis.org/wiki/OEIS_format_for_decimal_representation_of_constants, constants can have small negative, large negative, or large positive offsets. However, in these cases, the `cons` link just doesn't print neither the decimal point nor any other indication of the exponent of the number (e. g. using scientific notation). See https://oeis.org/A322578 (offset 24) and https://oeis.org/A348019 (offset -1).

**Comment by rsc** [comment]
Fixed.
