### ISSUE TITLE
Show sequence names in draft lists

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#2]
This is a proposal of an enhancement.

It would be convenient for editors to know the name of the sequences in the draft list to choose the ones they can/want to work with. Since for new sequences the last approved name is "Allocated for ...", the name from the current version rather than from the last approved version should be shown.

Open question: in which way exactly these names should be displayed? A possible answer: at least as `title`s for links (currently A-number links in the draft lists have no titles).

**Comment by rsc** [comment]
Fixed.
