### ISSUE TITLE
Inconsistent behavior between shortened A numbers in sequence pages and drafts pages.

### ISSUE THREAD

**Issue by winstonDeGreef** [oeis/oeis#20]
`https://oeis.org/A1` will redirect to `https://oeis.org/A000001` but `https://oeis.org/draft/A1` will not redirect and just show the data for `A000001`. This is inconsistent and I believe that both should redirect.

**Comment by winstonDeGreef** [comment]
Also `/A0000123` will redirect to `A000123` but the draft page will not redirect.

**Comment by m-f-h** [comment]
> `https://oeis.org/A1` will redirect to `https://oeis.org/A000001` but `https://oeis.org/draft/A1` will not redirect and just show the data for `A000001`. This is inconsistent and I believe that both should redirect.

seems fixed, at least I can't reproduce as of today:
https://oeis.org/draft/A1 indeed gives the page with title
## Draft edits for [A000001](https://oeis.org/A000001)
<center>
(Underlined text is an addition; strikethrough text is a deletion.)

(No pending changes for [A000001](https://oeis.org/A000001).)</center>

**Comment by zabolotskii** [comment]
No, it's not fixed: the (quite subtle and not terribly important) point of this issue is that even though the correct page is displayed, there is no redirect from https://oeis.org/draft/A1 to the canonical URL https://oeis.org/draft/A000001; in other words, https://oeis.org/draft/A1 is an alias (while https://oeis.org/A1 is a redirect).

**Comment by m-f-h** [comment]
Right, now I understand better what you meant.
Maybe URLs like oeis.org/Axxx are rewritten directly by the web server as oeis.org/A000xxx, but others like /draft/Axxx are maybe becoming something like /draft.php?id=1 (morally -- maybe not PHP but cgi or whatever.)
But I'm just guessing... Anyway, it seems more of an "aesthetical" problem than really an issue in any way.

**Comment by rsc** [comment]
Fixed.
