### ISSUE TITLE
I propose to resize that image.

### ISSUE THREAD

**Issue by ghost** [oeis/oeis#22]
On the search page there is no separation between the bar and the top image. And that causes errors. I propose to resize that image and leave a free space between the image and the search bar.

**Comment by ghost** [comment]
To my taste the whole design seems old-fashioned and not very functional. To me, the whole litany of "thanks to the Donors", "thanks to our Creator", "thanks to the Volunteers", makes it clear that Harvard must have been founded by very-very religious people.

**Comment by zabolotskii** [comment]
I support the original idea (accidental clicking the logo instead of the search bar is a real, quite annoying problem) [edit: Winston's suggestion below is better] and disapprove of the flame comments and self-reactions.

**Comment by simonarandaGH** [comment]
These people remind me of the Jedi. "Feel the Sequence, Luke!. 
I wouldn't be surprised to find a reviewer named Kenobi or Anakin.

**Comment by simonarandaGH** [comment]
There is a picture of Yoda inside his hut surrounded by papers, wearing genuine Jedi crocodile skin shoes.

**Comment by winstonDeGreef** [comment]
instead of resizing the image, I think that some margin should be added to it . Something like
![image](https://github.com/oeis/oeis/assets/71840364/bb725923-8e16-4d98-b9db-6e7002c22e57)
instead of
![image](https://github.com/oeis/oeis/assets/71840364/b52a2b0e-59f4-48a2-8e76-ce8ac9c738cb)

**Comment by rsc** [comment]
I added some spacing as suggested. Doing more is a bit contentious.

**Comment by zabolotskii** [comment]
Unfortunately it didn't solve the problem because the newly added margin is still a part of the hyperlink. Maybe add margin above the search bar instead?

**Comment by rsc** [comment]
Oops. Fixed again.
