### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#24]
There is a thing which is unclear in our legal documents.

[The OEIS Contributor's License Agreement](https://oeis.org/wiki/The_OEIS_Contributor%27s_License_Agreement) says that contributors grant to the Foundation and to OEIS Users license to do some things to the extent they are licensed under the OEIS EULA. [The OEIS EULA](https://oeis.org/wiki/The_OEIS_End-User_License_Agreement), in turn, says that the OEIS is made available under the CC BY-SA 4.0 license. The question: the Contributor's License Agreement implies that the license that applies to the contributed content is the license specified by the EULA at the moment 
(a) when the end-user uses the content, or
(b) when the contributor contributes the content?

In the case (a), the OEIS Foundation has the ability to change the license in the EULA in any way, which can be useful (cf. [the recent change](https://oeis.org/w/index.php?title=The_OEIS_End-User_License_Agreement&diff=1653351&oldid=1599470)). (The content previously published under the old license can still be used on its terms, of course.) However in that case any content licensed under e.g. CC BY-SA cannot be imported into the OEIS (except by its copyright holders, of course) because contributors can only grant the Foundation the right to license the content under CC BY-SA, not any other license.

In the case (b), we can import content licensed under CC BY-SA, CC BY, etc., but the Foundation cannot freely change the license in the EULA.

I can imagine that the answer to this question is smth like "it was (a) before, but it is (b) now, even though the wording of the Contributor's License Agreement didn't change". I am not a lawyer and cannot tell if it's legally OK.

**Comment by rsc** [comment]
The EULA applies to contributors. As it says in section 3, contributors should be contributing only material that they are legally entitled to contribute. This typically means material you authored yourself. Materials from outside sources should be imported into the OEIS.

**Comment by zabolotskii** [comment]
Unfortunately, the issue has not been addressed. Let's set aside the issue of material from outside sources for a while and consider me, a contributor. Suppose I am willing to grant the OEIS Foundation the right to distribute my contribution on certain terms (e.g. on the conditions of CC BY-SA 4.0 from the current EULA) but not others (e.g. not on the conditions of CC BY-NC 3.0).

The Contributor's License Agreement (CLA) can be interpreted in two ways, (a) and (b) from the original post.
* If the interpretation (b) is correct, then I can be certain that the Foundation will always distribute my contribution on the terms of CC BY-SA 4.0, as I wish.
* However if interpretation (a) is correct, this means that the Foundation can edit the EULA at any time and just start distributing my contribution on different terms. In that case, I might decide not to contribute.

Thus, the question I asked is substantial regardless the issue of materials from outside sources.

Now back to materials from the outside sources (even though, as I said, the main question doesn't depend on this aspect). I believe that I am legally entitled to grant _a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, make Adaptations, publicly display, publicly perform, sublicense, and distribute_ materials on the terms of CC BY-SA 4.0 if they were already published on the terms of CC BY-SA 4.0, even if the author is someone else. Sections 2(a)(1) and 2(a)(5) of [the license](https://creativecommons.org/licenses/by-sa/4.0/legalcode.en) explicitly entitle me to do this.
