### ISSUE TITLE
Add line break after terms

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#25]
Currently, the terms of any sequence in the Data field are immediately followed by the links: "(list; graph; refs; listen; history; edit; text; internal format)". Adding a line break between the sequence terms and these links will have the following benefits:

1. (major) It will become possible to select all terms (and nothing else) by a triple-click.
2. (minor) When the mouse cursor is hovered over a link and the user switches (using keyboard) to a different browser tab (also with a sequence), the cursor will often stay over the analogous link. This allows e.g. quickly switching multiple tabs with sequences to the editing mode, and doing other uniform actions.

The only drawback is the additional vertical space spent on the line with links in some cases, which is small.

**Comment by rsc** [comment]
Not entirely sure about this, but happy to try it. Done.

**Comment by zabolotskii** [comment]
I am now using the triple-click all the time. It is ridiculous to think that there was a time it wasn't possible. Thanks!
