### ISSUE TITLE
Links in the footer

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#26]
The link "more" in the footer leads to the page https://oeis.org/more.html , which says "This was an obsolete page and the content has been deleted". This link should be removed or replaced by something useful.

The links "Browse" and "WebCam" lead to the same page. Only one should be retained.

(reported by Robert Israel in the OEIS-EiC mailing list)

**Comment by rsc** [comment]
Removed.

**Comment by zabolotskii** [comment]
Thanks but the "Browse" + "WebCam" issue is still there.

**Comment by rsc** [comment]
Deleted Browse; thanks.
