### ISSUE TITLE
User names surrounded by underscores are not always turned into links

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#29]
As of now, in some sequence entries, in the Links section, the user names surrounded by underscores are not turned into links (as normally should happen). See, for example, https://oeis.org/A317231 (\_Robert Israel\_) or https://oeis.org/A028931 (\_Daniel E. Loeb\_). On the other hand, e.g. https://oeis.org/A002913 (Per H. Lundow) is not affected.

**Comment by rsc** [comment]
It wasn't linking names before the final </a>. Fixed.
