### ISSUE TITLE
Check b-files for validity

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#3]
This is a proposal of an enhancement.

Currently some checks are implemented, but many violations of the [loose b-file format](https://oeis.org/wiki/User:Charles_R_Greathouse_IV/Format#b-files) are still to be caught automatically.
For example, I once accidentally uploaded a b-file with O's instead of some 0's; and every now and then someone uploads a b-file with lines longer than 1000 characters or without a line break at the end.

**Comment by that-german** [comment]
An almost trivial piece of perl can do the job, including fixing some minor errors like leading or trailing blanks. I am willing to write it.

**Comment by manman4** [comment]
In principle, only numbers up to 1000 digits should be allowed to be uploaded, but there should be exceptions.
Therefore, I think the decision should be left to the approver who conducts the review.

**Comment by zabolotskii** [comment]
> In principle, only numbers up to 1000 digits should be allowed to be uploaded, but there should be exceptions. Therefore, I think the decision should be left to the approver who conducts the review.

I'm not aware of any single case when a **b**-file with a term with more than 1000 digits has been explicitly allowed by an editor.

(Anyway, thanks for the feedback, it's important.)

**Comment by gfis** [comment]
I ran a `wc -L` over all b-files. There are some 585 b-files with line lengths > 1050. The top lengths are in:
```
35673 bfile/b326609.txt
19718 bfile/b299104.txt
17562 bfile/b127181.txt
7523 bfile/b269253.txt
7123 bfile/b270520.txt
5977 bfile/b286037.txt
5946 bfile/b279330.txt
5742 bfile/b279121.txt

```
If such data are deemed reasonable by the authors and editors, an extension of the b-file format would be desirable where lines are broken with a trailing "\", like in Maple, MMA etc.

**Comment by zabolotskii** [comment]
*trailing "\\"?

Anyway, I agree that some limitations could be revisited, but we can do it all gradually. Such things as lines with words instead of numbers, like lines 282 nd 283 in https://oeis.org/A039926/b039926_1.txt , definitely should not be allowed.

**Comment by rsc** [comment]
The b-files were already checked for being an extension of the existing sequence and having indexes in increasing order. I've added a check for b-files without a terminating newline (indicating possible truncation) as well as for sequence values that are not decimal numbers.

**Comment by zabolotskii** [comment]
In https://oeis.org/A298562 , last October, a user uploaded a correct b-file but then accidentally copy-pasted incorrect Data. This got through review and approval without any difficulties, and was only corrected later because I noticed this. This is the kind of things which should better be caught before being published. Sometimes people correctly correct the Data but forget to correct the b-file, which is also not detected automatically, I believe. Hence I would like to reopen this issue (which Github doesn't allow me to do, since I am not a member of the oeis organization here).
