### ISSUE TITLE
It is too easy to accidentally post a pink-box comment twice

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#31]
Quoting Jon from https://oeis.org/history?seq=A354672 :
> (There’s a bug in the interface here — lamented for years, but still not fixed — that makes it very easy to accidentally post the same comment two or more times. It happens to me a lot.) 😕

I believe this happens if one clicks "Add note to discussion only" twice (before the first click triggers refreshing the page).

**Comment by m-f-h** [comment]
It can appear
- when you click twice, which in turn can happen
- - when you are impatient
- - on the mobile device, often/usually/(almost?)always the first click only takes you out of the "enter text" mode and you *have to* click twice to submit the comment (once), but sometimes the "almost always" happens and the first click will submit, but often it takes some time before the blue "loading..." line starts to appear on the top of the screen indicating that the form has indeed been submitted and is being processed (and/or waiting for the page to refresh)
- when, after submitting a comment, you use the "back" function of the browser to come back to the editing form (of course I know you shouldn't) ; when you go back only one step you are on the "same page" as *after* the submission of the edit, but the earlier submitted comment is "already" (still) filled in.

As a conclusion, I think that if it could be possible, it would be nice to check whether a submitted "pink box" is identical (say, up to white space) with the previously submitted one, and in that case not consider it.

**Comment by rsc** [comment]
I changed the display to omit the duplicate pink-box comments, so even old duplicates are gone (from view at least).

<img width="765" alt="Screenshot 2024-09-18 at 11 15 02 AM" src="https://github.com/user-attachments/assets/52103e13-266a-4ac3-a676-3ce310bea988">

**Comment by zabolotskii** [comment]
As another consequence of this change, only the last of a series of OEIS server automated reminders (in a draft which is left in the "editing" status for a long time) is now displayed. I don't know if this is intentional, but this is good!

**Comment by m-f-h** [comment]
I also think it's a good thing that the old and hence obsolete automatic reminders are deleted. 

but if the intention was to avoid pink box messages unintentionally sent twice in a row, it should only discard the second of immediately consecutive duplicates (or, only between two successive "approvals"), not look for any duplicates spread across the history.

Someone might intentionally copy an old pink box messag that "disappeared" from the "draft" page after edits were approved,
but which actually remained relevant (unresolved issue to be fixed).

**Comment by zabolotskii** [comment]
> it should only discard the second of immediately consecutive duplicates

Apparently it works exactly like this: e.g. in https://oeis.org/draft/A366244 the two identical automatic reminders are shown, because there was another comment between them, by Antti. So everything is fine.

**Comment by m-f-h** [comment]
OK, sorry, I misunderstood "even old duplicates are gone".
Perfect, thanks & kudos to @rsc !
