### ISSUE TITLE
insert anchors in section titles of "Axxx/table" pages

### ISSUE THREAD

**Issue by m-f-h** [oeis/oeis#32]
If we added an "id" in the section titles of the `/table` pages, as for example in https://oeis.org/A002260/table,
```
<h2><a href="/A002260" id="square">A002260</a> as a square array</h2>
```
it would be possible to link directly to a given formatting, using https://oeis.org/A002260/table#square

For the first subsection ("triangular array"), it's not that useful, but for the second one, as shown above (arguably the most frequent case), it certainly is, and maybe also for the last section, viz.
```
<h2><a href="/A002260" id="triangle">A002260</a> as an upper right triangle</h2>
```

**Comment by rsc** [comment]
Done although it doesn't do as much as you might hope.
