### ISSUE TITLE
Text-only search shows an incorrect message

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#34]
When a user runs a search which includes no sequence terms and returns no results, like https://oeis.org/search?q=asdfghjkl, the message "_Advanced lookups are not available now. Please try again in a few minutes._" is always displayed. However the advanced lookup is of course available, it's just not needed in this case.

**Comment by rsc** [comment]
Fixed, thanks.

**Comment by zabolotskii** [comment]
Thanks but it also happens when a search contains a wildcard and finds nothing: https://oeis.org/search?q=142857%2C_%2C314159
