### ISSUE TITLE
OEIS.ORG and the search engine always suggests: 1,2,3,6,11,23,47

### ISSUE THREAD

**Issue by UserJAMBO** [oeis/oeis#38]
OEIS.ORG and the search engine always suggests:
1,2,3,6,11,23,47,106.   It is absurd. 
How do you delete that? Why does it always come up? 
Is it a cookie problem? Java problem?
A search engine bar should always appear empty.

**Comment by zabolotskii** [comment]
The OEIS main page without the pre-filled search bar is available at the URL https://oeis.org/?blank=1
This fact suggests that the pre-filled search bar is not a bug but a feature (basically a hint for new users).

That said, I too dislike this feature, especially on mobile.

A hint for new users on the main page is important, but we can have it on the main page in a different way, avoiding a minor but irritating inconvenience for everybody else, e.g. as follows. The search bar is empty by default. Below the search bar and the "Search" button, we have something like:

> Try 1, 2, 3, 6, 11, 23, 47, 106, 235 and press Search

, where the terms are styled as a link with dashed underline, and upon clicking on them they get inserted into the search bar.

**Comment by UserJAMBO** [comment]
It looks like a superstition, like a native Indian's medicine bag.
Anyway, one day Google will discover the potential of the OEIS.

**Comment by m-f-h** [comment]
I step in late, but ... I find this annoying too (as mentioned, it is somewhat painful to delete the useless contents esp. on mobile devices).
I suggest next to the [Search] button, there might be a [Clear] button.
