### ISSUE TITLE
Indexing oeisf.org

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#7]
Currently search engines and web archives do not process the website of the OEIS Foundation, [oeisf.org](https://oeisf.org), because [its robots.txt](https://oeisf.org/robots.txt) disallows it. It would be better to allow it.

**Comment by rsc** [comment]
Fixed.

**Comment by zabolotskii** [comment]
Hmmm, Google now indexes pages like https://oeisf.org/A009766 (sic: oeis**f**!), which probably should be fixed by tuning robots.txt further.
