### ISSUE TITLE
"the system may ignore a line containing a non-ASCII character without warning you"

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#8]
Currently, [the Style Sheet says](https://oeis.org/wiki/Style_Sheet#Non-ASCII_characters): _Don't use non-ASCII characters! They just cause trouble, and the system may ignore a line containing a non-ASCII character without warning you._

I don't know whether this is correct; if no, it probably should be corrected; if yes, "ignoring a line containing a non-ASCII character without warning" seems to be a recipe for losing contributors' data, which could be very frustrating.

Yes, the Style Sheet lists some exceptions, but it gives no clue on how it works exactly (and, in particular, gives no explicit guarantee that the "allowed" lines with non-ASCII characters won't be silently ignored).

---
Update: indeed, some non-ASCII characters are corrupted, see [here](https://oeis.org/history?seq=A002913): in edit # 56, I add a Japanese work title which is displayed correctly in the view mode but corrupted in the history mode; in edit # 57, it is corrupted completely even though I didn't touch it.

**Comment by rsc** [comment]
The software and web site do support UTF-8 characters. The problem is that browsers are not so good at always sending UTF-8. Most non-ASCII UTF-8 characters are fine. I am not sure what is going on in the Japanese URL text you pointed out.

**Comment by zabolotskii** [comment]
The Japanese title in [A2913](https://oeis.org/A002913) was saved and published successfully on the second attempt. However, the history page still displays �s, so this indicates a server software bug rather than a browser bug. It only happens with CJK characters though. (Other web services, like the website where we are now or [this simple app](https://github.com/colt-browning/basic_server), seem to handle CJK just fine.)

Anyway, if "the system may ignore a line containing a non-ASCII character without warning you" is no longer true (at least in general), the [Non-ASCII characters](https://oeis.org/wiki/Style_Sheet#Non-ASCII_characters) section of the OEIS Style Sheet should be updated. How about the following text?
  > In formulas, use only ASCII characters in accordance with the [[#Spelling and notation]] section. For example, do not use Greek letters (&#960;, &#931;), Unicode symbols like not-equal-to (&#8800;), less-than-or-equal-to (&#8804;), greater-than-or-equal-to (&#8805;), the 3-dot ellipsis character (&#8230;), etc.
  >
  > Non-ASCII characters can be used for names of authors, OEIS contributors, places, institutions, etc., for example: 
  > * Geneviève Paquin, Dénombrement de multigraphes enrichis, Mémoire, Math. Dept., Univ. Québec à Montréal, 2004.
  > * A033308 Decimal expansion of Copeland-Erdős constant: concatenate primes. (Links section: Mikołaj Morzy, Tomasz Kajdanowicz, Przemysław Kazienko, ...)
  >
  > In general, the OEIS software supports Unicode (except for the search). However, using characters which take more than 2 bytes in the UTF-8 encoding, such as Japanese characters, sometimes causes issues and data corruption.

**Comment by rsc** [comment]
I don't know what happened in that old edit. Probably the browser did send bad UTF-8. In any event, I've updated the style guide to make clear that not using Unicode in mathematical text is a style decision not a technical one.
