### ISSUE TITLE
Improve diffs

### ISSUE THREAD

**Issue by zabolotskii** [oeis/oeis#9]
This is a proposal of an enhancement which might require significant effort to implement (or not: possibly just using a good third-party library will solve the issue).

The diffs are far from perfect (in particular, worse than MediaWiki's; however, MW diffs are two-column, not inline).

Examples are below.

Consider my edit # 16 [here](https://oeis.org/history?seq=A007207): I merely added minuses to all positive terms and removed them from the negative terms, so an optimal diff would look like this:
<del>-</del>1, 0, 0, <ins>-</ins>2, 0, <ins>-</ins>12, <del>-</del>2, <ins>-</ins>78, <del>-</del>24, <ins>-</ins>548, <del>-</del>228, <ins>-</ins>4050, <del>-</del>2030, <ins>-</ins>30960, <del>-</del>17670, <ins>-</ins>242402, <del>-</del>152520, <ins>-</ins>1932000, <del>-</del>1312844, <ins>-</ins>15612150, <del>-</del>11297052, <ins>-</ins>127551884, <del>-</del>97291026, <ins>-</ins>1051478274, <del>-</del>838994486, <ins>-</ins>8732657724, <del>-</del>7246304736, <ins>-</ins>72983051674, <del>-</del>62686156026, <ins>-</ins>613243234224, <del>-</del>543146222970
while the actual diff produced by the OEIS software is:
<del>-</del>1, 0, 0<del>, </del><ins>, -</ins>2, 0<del>, </del><del>12</del>, -<del>2</del><ins>12</ins>, <del>78</del><ins>2</ins>, -<del>24</del><ins>78</ins>, <del>548</del><ins>24</ins>, -<del>228</del><ins>548</ins>, <del>4050</del><ins>228</ins>, -<del>2030</del><ins>4050</ins>, <del>30960</del><ins>2030</ins>, -<del>17670</del><ins>30960</ins>, <del>242402</del><ins>17670</ins>, -<del>152520</del><ins>242402</ins>, <del>1932000</del><ins>152520</ins>, -<del>1312844</del><ins>1932000</ins>, <del>15612150</del><ins>1312844</ins>, -<del>11297052</del><ins>15612150</ins>, <del>127551884</del><ins>11297052</ins>, -<del>97291026</del><ins>127551884</ins>, <del>1051478274</del><ins>97291026</ins>, -<del>838994486</del><ins>1051478274</ins>, <del>8732657724</del><ins>838994486</ins>, -<del>7246304736</del><ins>8732657724</ins>, <del>72983051674</del><ins>7246304736</ins>, -<del>62686156026</del><ins>72983051674</ins>, <del>613243234224</del><ins>62686156026</ins>, -<ins>613243234224</ins><ins>, </ins>543146222970
 
Or consider a well-known problem of inserting a non-alphabetical, non-digit character (in particular, a space) into a sequence of other such characters. See, e. g., Jon E. Schoenfield's edit # 1829 [here](https://oeis.org/history?seq=A000108), where the optimal diff for one of its lines would be
G.f.: (1-sqrt(1-4\*x))/(2\*x)<ins> </ins>=<ins> </ins>G(0) where G(k)<ins> </ins>=<ins> </ins>1<ins> </ins>+<ins> </ins>(4\*k+1)\*x/(k+1-2\*x\*(k+1)\*(4\*k+3)/(2\*x\*(4\*k+3)+(2\*k+3)/G(k+1))); (continued fraction). - \_Sergei N. Gladkovskii\_, Nov 30 2011
while the actual diff is
G.f.: (1-sqrt(1-4\*x))/(2\*x<del>)=</del><ins>) = </ins>G(0) where G(k<del>)=</del><ins>) = </ins>1<del>+(</del><ins> + (</ins>4\*k+1)\*x/(k+1-2\*x\*(k+1)\*(4\*k+3)/(2\*x\*(4\*k+3)+(2\*k+3)/G(k+1))); (continued fraction). - \_Sergei N. Gladkovskii\_, Nov 30 2011

This is especially annoying when you just extend the sequence data, so the diff should be simply "untouched terms, followed by the new terms", but the actual diff is something more complicated, like [here](https://oeis.org/history?seq=A005874) in edit # 39.

One more very typical example: my edit # 30 [here](https://oeis.org/history?seq=A246966). I added one new line and merely replaced "http" by "https" in the other line. The diff shows it in a suboptimal way.

**Comment by ghost** [comment]
I think the underlying problem is that the workflow is too rigid. Obviously you have to maintain a style in the published edition. But there is no reason to fix the intermediate formats so much. I think they need to be more flexible. This is what leads to so much discussion with volunteers.

**Comment by rsc** [comment]
Re ghost's comment, there is no distinction between "published edition" and "web site" anymore. It's not like there are paid staff to come around and clean up what's left after the "volunteers" have made changes. We are all volunteers, and there are standards we aim to maintain.

**Comment by rsc** [comment]
I spent a while looking into this and improved the diffs considerably. 

Before:
<img width="785" alt="Screenshot 2024-09-18 at 10 37 13 AM" src="https://github.com/user-attachments/assets/862f85f6-cb49-4f34-b33b-c8938281b5cd">

After:
<img width="768" alt="Screenshot 2024-09-18 at 10 37 19 AM" src="https://github.com/user-attachments/assets/cb7eeac6-a898-4def-821f-11307b6492a6">

And another after (I didn't save the before, but we all remember it was terrible):
<img width="764" alt="Screenshot 2024-09-18 at 11 05 37 AM" src="https://github.com/user-attachments/assets/34624262-51aa-454d-809d-5388079bc051">

The example of A246966 rev 30 is also fixed, in that the diff will now no longer try to align the old and new link lines at all, but that decision about which line became which other line is recorded in the actual history, so it's only fixed for future edits, not old ones.

**Comment by rsc** [comment]
Actually that last screenshot is a little old. Here is the current one, which is even nicer:


<img width="766" alt="Screenshot 2024-09-18 at 11 08 43 AM" src="https://github.com/user-attachments/assets/15d38f07-ef21-4e92-a19e-b55f25b0338a">

**Comment by zabolotskii** [comment]
Thank you so much. This is amazing.
